config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :authors
    resources :books
    resources :accounts
    resources :parts
    resources :suppliers
    resources :assemblies
  end

  resources :parts
  resources :assemblies

  resources :authors do
    get 'relatorio', on: :collection
  end

  resources :books do
    get 'relatorio', on: :collection
  end

  resources :suppliers do
    resource :account, controller: 'accounts'
    get 'relatorio', on: :collection
  end
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :supplier
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, message: I18n.t('model.part.greater_than_or_equal_to') }
  has_and_belongs_to_many :assemblies

end

app/controllers/api/parts_controller.rb
class Api::PartsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @parts = Part.all
    render json: @parts
  end

  def show
    @part = Part.find(params[:id])
    render json: @part
  end

  def create
    @part = Part.new(part_params)

    if @part.save
      render json: @part, status: :created
    else
      render json: @part.errors, status: :unprocessable_entity
    end
  end

  def update
    @part = Part.find(params[:id])

    if @part.update(part_params)
      render json: @part
    else
      render json: @part.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @part = Part.find(params[:id])
    @part.destroy

    head :no_content
  end

  private

  def part_params
    params.require(:part).permit(:title, :description)
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: %i[ show edit update destroy ]

  def index
    @parts = Part.all
  end

  def show
  end

  def new
    @part = Part.new
  end

  def create
    @part = Part.new(part_params)

    if @part.save
      redirect_to @part, notice: I18n.t('part.controller.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @part.update(part_params)
      redirect_to @part, notice: I18n.t('part.controller.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @part.destroy

    redirect_to parts_url, notice: I18n.t('part.controller.destroy')
  end

  private
  def set_part
    @part = Part.find(params[:id])
  end
  def part_params
    params.require(:part).permit(:title, :description, :supplier_id, :price)
  end
end

app/views/parts/_form.html.erb
<%= form_with(model: @part) do |form| %>
  <% if part.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(part.errors.count, "error") %> <%= I18n.t('part.error') %>:</h2>

      <ul>
        <% part.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :supplier_id, style: "display: block" %>
    <%= form.collection_select :supplier_id, Supplier.all, :id, :name %>
  </div>

  <div>
    <%= form.label :price, style: 'display: block' %>
    <%= form.number_field :price, step: 'any' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/_part.html.erb
<div id="<%= dom_id part %>">
  <p>
    <strong><%= I18n.t('part._part_supplier') %>:</strong>
    <%= part.supplier.name %>
  </p>

  <p>
    <strong><%= I18n.t('activerecord.attributes.part.title') %>:</strong>
    <%= part.title %>
  </p>

  <p>
    <strong><%= I18n.t('activerecord.attributes.part.description') %>:</strong>
    <%= part.description %>
  </p>

  <p>
    <strong><%= I18n.t('activerecord.attributes.part.price') %>:</strong>
    <%= part.price %>
  </p>

</div>

app/views/parts/edit.html.erb
<h1><%= I18n.t('part.view_edit_title') %></h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to I18n.t('part.show'), part_path(@part) %> |
  <%= link_to I18n.t('part.back'), parts_path %>
</div>

app/views/parts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= I18n.t('part.view_index_title') %></h1>

<div id="parts">
  <% @parts.each do |part| %>
    <%= render part %>
    <p>
      <%= link_to I18n.t('part.show'), part %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to I18n.t('part.new'), new_part_path %> |

app/views/parts/new.html.erb
<h1><%= I18n.t('part.view_new_title') %></h1>

<%= render "form", part: @part %>

<br>

<div>
  <%= link_to I18n.t('part.back'), parts_path %>
</div>

app/views/parts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @part %>
<div>
  <strong><%= I18n.t('part.view_show.assembly_associated') %>:</strong>
  <ul>
    <% @part.assemblies.each do |assembly| %>
      <li><%= link_to assembly.name, assembly_path(assembly) %></li>
    <% end %>
  </ul>
</div>

<div>
  <%= link_to I18n.t('part.back'), parts_path %> |
  <%= link_to I18n.t('part.edit'), edit_part_path(@part) %> |

  <%= button_to I18n.t('part.destroy'), part_path(@part), method: :delete %>
</div>