config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :authors
    resources :books
    resources :accounts
    resources :parts
    resources :suppliers
    resources :assemblies
  end

  resources :parts
  resources :assemblies

  resources :authors do
    get 'relatorio', on: :collection
  end

  resources :books do
    get 'relatorio', on: :collection
  end

  resources :suppliers do
    resource :account, controller: 'accounts'
    get 'relatorio', on: :collection
  end
end

app/models/author.rb
require 'cpf_cnpj'
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  validate :cpf_must_be_valid

  private

  def cpf_must_be_valid
    unless CPF.valid?(cpf)
      errors.add(:cpf, "cpf is not valid")
    end
  end
end

app/controllers/api/authors_controller.rb
# app/controllers/api/authors_controller.rb
class Api::AuthorsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    authors = Author.all
    render json: authors, except: %i[created_at updated_at]
  end

  def show
    author = Author.find(params[:id])
    render json: author
  end

  def create
    author = Author.new(author_params)

    if author.save
      render json: author, status: :created, except: %i[created_at updated_at]
    else
      render json: { errors: author.errors }, status: :unprocessable_entity
    end
  end

  def update
    author = Author.find(params[:id])

    if author.update(author_params)
      render json: author, except: %i[created_at updated_at]
    else
      render json: { errors: author.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    author = Author.find(params[:id])
    author.destroy
    head :no_content
  end

  private

  def author_params
    params.require(:author).permit(:name, :cpf)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]
  def index
    @authors = Author.all
  end
  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to author_url(@author), notice: I18n.t('author.controller.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @author.update(author_params)
      redirect_to author_url(@author), notice: I18n.t('author.controller.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @author.destroy

    redirect_to authors_url, notice: I18n.t('author.controller.destroy')
  end

  def relatorio
    @authors = Author.all
  end

  private
  def set_author
    @author = Author.find(params[:id])
  end

  def author_params
    params.require(:author).permit(:name, :cpf)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<div id="<%= dom_id author %>">
  <p>
    <strong><%= I18n.t('activerecord.attributes.author.name') %>:</strong>
    <%= author.name %>
  </p>

  <p>
    <strong><%= I18n.t('activerecord.attributes.author.cpf') %>:</strong>
    <%= author.cpf %>
  </p>

</div>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <% if author.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(author.errors.count, "error") %> <%= I18n.t('author.error') %>:</h2>

      <ul>
        <% author.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1><%= I18n.t('author.edit_title') %></h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to I18n.t('author.show'), @author %> |
  <%= link_to I18n.t('author.back'), authors_path %>
</div>

app/views/authors/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to I18n.t('author.relatorio.title'), relatorio_authors_path %>

<h1><%= I18n.t('author.index_title') %></h1>

<div id="authors">
  <% @authors.each do |author| %>
    <%= render author %>
    <p>
      <%= link_to I18n.t('author.show'), author %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to I18n.t('author.new'), new_author_path %>

app/views/authors/new.html.erb
<h1> <%= I18n.t('author.new_title') %></h1>

<%= render "form", author: @author %>

<br>

<div>
  <%= link_to I18n.t('author.back'), authors_path %>
</div>

app/views/authors/relatorio.html.erb
<h1><%= I18n.t('author.relatorio.title') %></h1>

<div class="authors-container">
  <% @authors.each do |author| %>
    <div class="author-box">
      <div class="author-info">
        <p><strong><%= I18n.t('author.relatorio.author') %>:</strong> <%= author.name %></p>
        <p><strong>CPF:</strong> <%= author.cpf %></p>
        <p><strong><%= I18n.t('author.relatorio.total_books') %>:</strong> <%= author.books.count %></p>
      </div>

      <div class="books-info">
        <table>
          <thead>
          <tr>
            <th><%= I18n.t('author.relatorio.book_title') %></th>
            <th>ISBN</th>
          </tr>
          </thead>
          <tbody>
          <% author.books.each do |book| %>
            <tr>
              <td><%= book.title %></td>
              <td><%= book.isbn %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>

    <hr class="separator">
  <% end %>
</div>

app/views/authors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @author %>

<div>
  <h2><%= I18n.t('author.view_show.books_from_author') %>:</h2>
  <ul>
    <% @author.books.each do |book| %>
      <li><%= book.title %></li>
    <% end %>
  </ul>

  <%= link_to I18n.t('author.edit'), edit_author_path(@author) %> |
  <%= link_to I18n.t('author.back'), authors_path %>

  <%= button_to I18n.t('author.destroy'), @author, method: :delete %>
</div>