config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :authors
    resources :books
    resources :accounts
    resources :parts
    resources :suppliers
    resources :assemblies
  end

  resources :parts
  resources :assemblies

  resources :authors do
    get 'relatorio', on: :collection
  end

  resources :books do
    get 'relatorio', on: :collection
  end

  resources :suppliers do
    resource :account, controller: 'accounts'
    get 'relatorio', on: :collection
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :assembly

  validate :isbn_must_be_valid

  private

  def isbn_must_be_valid
    cleaned_isbn = isbn.gsub(/\D/, '')
    return if valid_isbn_10?(cleaned_isbn) || valid_isbn_13?(cleaned_isbn)
    errors.add(:isbn, "is not valid")
  end

  def valid_isbn_10?(number)
    return false unless number =~ /\A\d{9}[0-9X]\z/

    sum = 0
    number.chars.each_with_index do |char, index|
      sum += (char == 'X' ? 10 : char.to_i) * (10 - index)
    end
    sum % 11 == 0
  end

  def valid_isbn_13?(number)
    return false unless number =~ /\A\d{13}\z/

    sum = 0
    number.chars.each_with_index do |char, index|
      sum += char.to_i * (index.even? ? 1 : 3)
    end
    sum % 10 == 0
  end
end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @books = Book.all.includes(:author)
    books_data = @books.map do |book|
      {
        id: book.id,
        nome_do_autor: book.author.name,
        title: book.title,
        isbn: book.isbn,
        montagem: book.assembly.name
      }
    end
    render json: books_data
  end

  def show
    @book = Book.find(params[:id])
    render json: @book
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      render json: @book, status: :created, except: [:updated_at, :created_at]
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      render json: @book, except: [:updated_at, :created_at]
    else
      render json: @book.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    head :no_content
  end

  private

  def book_params
    params.require(:book).permit(:title, :isbn, :author_id, :assembly_id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    if params[:query].present?
      if params[:search] == 'author'
        @books = Book.joins(:author).where('authors.name ILIKE ?', "%#{params[:query]}%")
      else
        @books = Book.where('title ILIKE ?', "%#{params[:query]}%")
      end
    else
      @books = Book.all
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: I18n.t('book.controller.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book, notice: I18n.t('book.controller.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_url, notice: I18n.t('book.controller.destroy')
  end

  def relatorio
    @books = Book.all
  end

  private
  def book_params
    params.require(:book).permit(:title, :isbn, :author_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong><%= I18n.t('activerecord.attributes.book.title') %>:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>isbn:</strong>
    <%= book.isbn %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author.name %>
  </p>
</div>

app/views/books/_form.html.erb
<%= form_with(model: @book) do |form| %>
  <% if @book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@book.errors.count, "error") %> <%= I18n.t('book.form_error') %>:</h2>

      <ul>
        <% @book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.collection_select :author_id, Author.all, :id, :name %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :isbn, style: "display: block" %>
    <%= form.text_field :isbn %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1><%= I18n.t('book.view_edit_title') %></h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to I18n.t('book.show'), book_path %> |
  <%= link_to I18n.t('book.back'), books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to I18n.t('book.view_index.report'), relatorio_books_path %>

<h1><%= I18n.t('book.view_index.title') %></h1>
<%= form_with url: books_path, method: :get, local: true do %>
  <div>
    <%= label_tag :search, I18n.t('book.view_index.search.find_by') + ":" %>
    <%= radio_button_tag :search, 'author', params[:search].nil? || params[:search] == 'author' %>
    <%= label_tag :search_author, I18n.t('activerecord.attributes.author.name') %>
    <%= radio_button_tag :search, 'title', params[:search] == 'title' %>
    <%= label_tag :search_title, I18n.t('activerecord.attributes.book.title') %>
  </div>
  <div>
    <%= label_tag :query, I18n.t('book.view_index.search.query') + ':' %>
    <%= text_field_tag :query, params[:query] %>
  </div>
  <div>
    <%= submit_tag I18n.t('book.view_index.search.filter') %>
  </div>
<% end %>
<hr>
<%= link_to I18n.t('book.new'), new_book_path %>


<% if @books.any? %>
  <div id="books">
    <% @books.each do |book| %>
      <%= render book %>
      <p>
        <%= link_to I18n.t('book.show'), book_path(id: book.id) %>
      </p>
      <hr>
    <% end %>
  </div>
<% else %>
  <p style="color: #B00100"> <%= I18n.t('book.view_index.search.any_book_found')%></p>
<% end %>

app/views/books/new.html.erb
<h1><%= I18n.t('book.view_new_title')%></h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to I18n.t('book.back'), books_path %>
</div>

app/views/books/relatorio.html.erb
<h1><%= I18n.t('book.view_index.report') %></h1>
<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>ISBN</th>
    <th>Assembly</th>
    <th>Parts</th>
    <th>Total cost</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.author.name %></td>
      <td><%= book.isbn %></td>
      <td><%= book.assembly.name %></td>
      <td>
        <ul>
          <% total_cost = 0 %>
          <% book.assembly.parts.each do |part| %>
            <li>
              <strong>Title:</strong> <%= part.title %><br>
              <strong>Description:</strong> <%= part.description %><br>
              <strong>Part Number:</strong> <%= part.part_number %><br>
              <strong>Price:</strong> <%= part.price %><br>
              <strong>Supplier:</strong> <%= part.supplier.name %><br>
              <strong><%= part.supplier.name %> - CNPJ:</strong> <%= part.supplier.cnpj %><br>
              <% total_cost += part.price %>
            </li>
          <% end %>
        </ul>
      </td>
      <td>$<%= total_cost %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book %>

<div>
  <%= link_to I18n.t('book.edit'), edit_book_path(@book) %> |
  <%= link_to I18n.t('book.back'), books_path(@book) %>

  <%= button_to I18n.t('book.destroy'), book_path(@book), method: :delete %>
</div>