config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    resources :authors
    resources :books
    resources :accounts
    resources :parts
    resources :suppliers
    resources :assemblies
  end

  resources :parts
  resources :assemblies

  resources :authors do
    get 'relatorio', on: :collection
  end

  resources :books do
    get 'relatorio', on: :collection
  end

  resources :suppliers do
    resource :account, controller: 'accounts'
    get 'relatorio', on: :collection
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_one :account, dependent: :destroy
  has_many :parts, dependent: :destroy

  validate :cnpj_must_be_valid


  private

  def cnpj_must_be_valid
    return if cnpj.blank?

    return if valid_cnpj?(cnpj)

    errors.add(:cnpj, 'não é válido')
  end

  def valid_cnpj?(cnpj)
    cnpj = cnpj.scan(/[0-9]/).join

    return false unless cnpj.length == 14
    return false if cnpj.chars.uniq.length == 1

    first_digit = calculate_digit(cnpj[0..11], [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2])
    second_digit = calculate_digit(cnpj[0..12], [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2])

    cnpj[12].to_i == first_digit && cnpj[13].to_i == second_digit
  end

  def calculate_digit(numbers, weights)
    sum = 0

    numbers.chars.each_with_index do |number, index|
      sum += number.to_i * weights[index]
    end

    mod = sum % 11
    mod < 2 ? 0 : 11 - mod
  end
end

app/controllers/api/suppliers_controller.rb
class Api::SuppliersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @suppliers = Supplier.all
    render json: @suppliers, except: %i[created_at updated_at]
  end

  def show
    @supplier = Supplier.find(params[:id])
    render json: @supplier.as_json(include: { account: { only: %i[bank number digit] } }, except: %i[created_at updated_at])
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      render json: @supplier, status: :created
    else
      render json: @supplier.errors, status: :unprocessable_entity
    end
  end

  def update
    @supplier = Supplier.find(params[:id])

    if @supplier.update(supplier_params)
      render json: @supplier, except: %i[created_at updated_at]
    else
      render json: @supplier.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @supplier = Supplier.find(params[:id])
    @supplier.destroy
    head :no_content
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :cnpj)
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[edit update destroy]

  def index
    if params[:filter_by] == 'name' && params[:query].present?
      @suppliers = Supplier.where('name ILIKE ?', "%#{params[:query]}%")
    elsif params[:filter_by] == 'account_number' && params[:query].present?
      @suppliers = Supplier.joins(:account).where('accounts.number ILIKE ?', "%#{params[:query]}%")
    elsif params[:filter_by] == 'author_name' && params[:query].present?
      @suppliers = Supplier.joins(parts: { assemblies: { book: :author } }).where('authors.name ILIKE ?', "%#{params[:query]}%").distinct
    else
      @suppliers = Supplier.all
    end
  end


  def show
    @supplier = Supplier.includes(:account).find(params[:id])
  end

  def new
    @supplier = Supplier.new
  end

  def edit; end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to supplier_url(@supplier), notice: I18n.t('supplier.controller.create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_url(@supplier), notice: I18n.t('supplier.controller.update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @supplier.destroy

    redirect_to suppliers_url, notice: I18n.t('supplier.controller.destroy')
  end

  def relatorio
    @suppliers = Supplier.all
  end
  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:name, :cnpj)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with(model: supplier) do |form| %>
  <% if supplier.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(supplier.errors.count, "error") %> <%= I18n.t('supplier.error') %>:</h2>

      <ul>
        <% supplier.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/suppliers/_supplier.html.erb
<div id="<%= dom_id supplier %>">
  <p>
    <strong><%= I18n.t('activerecord.attributes.supplier.name') %>:</strong>
    <%= supplier.name %>
  </p>
  <p>
    <strong>CNPJ:</strong>
    <%= supplier.cnpj %>
  </p>

</div>

app/views/suppliers/edit.html.erb
<h1><%= I18n.t('supplier.view_edit_title') %></h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to I18n.t('supplier.show'), @supplier %> |
  <%= link_to I18n.t('supplier.back'), suppliers_path %>
</div>

app/views/suppliers/index.html.erb
<p style="color: green"><%= notice %></p>

<%= link_to I18n.t('supplier.relatorio.title'), relatorio_suppliers_path %>

<h1><%= I18n.t('supplier.view_index_title') %></h1>
<%= form_with url: suppliers_path, method: :get, local: true do %>
  <div>
    <%= label_tag :filter_by, I18n.t('supplier.view_index.filter_by') + ":" %>
    <%= radio_button_tag :filter_by, 'name', params[:filter_by].nil? || params[:filter_by] == 'name' %>
    <%= label_tag :name, I18n.t('supplier.view_index.name') %>

    <%= radio_button_tag :filter_by, 'account_number', params[:filter_by] == 'account_number' %>
    <%= label_tag :account_number, I18n.t('supplier.view_index.account_number') %>

    <%= radio_button_tag :filter_by, 'author_name', params[:filter_by] == 'author_name' %>
    <%= label_tag :author_name, I18n.t('supplier.view_index.author_name') %>
  </div>

  <div>
    <%= label_tag :query, I18n.t('supplier.view_index.search_query') %>
    <%= text_field_tag :query, params[:query] %>
  </div>

  <div>
    <%= submit_tag I18n.t('helpers.filter.button') %>
  </div>
<% end %>


<% if @suppliers.any? %>
  <div id="suppliers">
    <% @suppliers.each do |supplier| %>
      <%= render supplier %>
      <p>
        <%= link_to I18n.t('supplier.show'), supplier %>
      </p>
      <hr>
    <% end %>
  </div>
<% else %>
  <p style="color: #B00100"><%= I18n.t('supplier.view_index.any_supplier_found') %></p>
<% end %>

<%= link_to I18n.t('supplier.new'), new_supplier_path %>

app/views/suppliers/new.html.erb
<h1><%= I18n.t('supplier.view_new_title') %></h1>

<%= render "form", supplier: @supplier %>

<br>

<div>
  <%= link_to I18n.t('supplier.back'), suppliers_path %>
</div>

app/views/suppliers/relatorio.html.erb
<h1><%= I18n.t('supplier.relatorio.title') %></h1>

<table>
  <thead>
  <tr>
    <th><%= I18n.t('activerecord.attributes.supplier.name') %></th>
    <th>Número da Conta</th>
    <th>Autores e Livros</th>
  </tr>
  </thead>
  <tbody>
  <% @suppliers.each do |supplier| %>
    <tr>
      <td><%= render supplier %></td>
      <td>
        <% if supplier.account %>
          <%= supplier.account.number %>
          <%= supplier.account.digit %>
        <% else %>
          <%= I18n.t('supplier.supplier_account') %>
        <% end %>
      </td>
      <td>
        <ul>
          <% supplier.parts.each do |part| %>
            <% part.assemblies.each do |assembly| %>
              <li>
                <%= assembly.book.author.name %>
                (<strong>cpf: </strong><%= assembly.book.author.cpf %>)
              </li>
              <ul>
                <% assembly.book.author.books.each do |book| %>
                  <li>
                    <%= book.title %> (<strong>isbn: </strong><%= book.isbn %>)
                  </li>
                <% end %>
              </ul>
            <% end %>
          <% end %>
        </ul>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/suppliers/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @supplier %>
<% if @supplier.account %>
  <%= @supplier.account.number %>
  <%= @supplier.account.digit %>
  <%= link_to "Acessar conta", supplier_account_path(@supplier) %>
<% else %>
  <%= I18n.t('supplier.supplier_account') %>
  <%= link_to "Criar conta", new_supplier_account_path(@supplier) %>
<% end %>

<div>
  <br>
  <%= link_to I18n.t('supplier.edit'), edit_supplier_path(@supplier) %> |
  <%= link_to I18n.t('supplier.back'), suppliers_path %>

  <%= button_to I18n.t('supplier.destroy'), @supplier, method: :delete %>
</div>